import { Command } from "./command";

export const COMMANDS: Command[] =  [
    {index: 'I_SSINIT', id: 1, name: 'Начать процедуру вхождения в связь по СКС'},
    {index: 'I_SSSTART', id: 2, name: 'Начать сеанс связи по СКС'},
    {index: 'I_SSSTOP', id: 3, name: 'Прекратить сеанс связи по СКС'},
    {index: 'I_RSSTART', id: 4, name: 'Начать сеанс связи по РСПИ'},
    {index: 'I_RSSTOP', id: 5, name: 'Прекратить сеанс связи по РСПИ'},
    {index: 'I_MDMBCK', id: 6, name: 'Выполнить резервное копирование'},
    {index: 'I_MDMSHTDN', id: 7, name: 'Останов МДМ'},
    {index: 'I_PRIUS', id: 9, name: 'Установить приоритет ИУС'},
    {index: 'I_PRKSPE', id: 10, name: 'Установить приоритет КСПЭ'},
    {index: 'I_PRTVS', id: 11, name: 'Установить приоритет ТВС'},
    {index: 'I_PRFDP', id: 12, name: 'Установить приоритет FDP'},
    {index: 'I_PRCLR', id: 13, name: 'Сбросить приоритет'},
    {index: 'I_TRVTVS', id: 14, name: 'Включить трансляцию ТВС'},
    {index: 'I_TRVSDI', id: 15, name: 'Включить трансляцию КСПЭ SDI'},
    {index: 'I_TRVHDMI', id: 16, name: 'Включить трансляцию КСПЭ HDMI'},
    {index: 'I_STPTVS', id: 17, name: 'Выключить трансляцию ТВС'},
    {index: 'I_STPSDI', id: 18, name: 'Выключить трансляцию КСПЭ SDI'},
    {index: 'I_STPHDMI', id: 19, name: 'Выключить трансляцию КСПЭ HDMI'},
    {index: 'I_CLRCCSDS', id: 20, name: 'Очистить очередь CCSDS-пакетов'},
    {index: 'I_REBTMDM', id: 21, name: 'Перезагрузка МДМ'},
    {index: 'I_REBTVID', id: 22, name: 'Перезагрузка Видеоплаты МДМ'},
    {index: 'I_ONPRM1', id: 111, name: 'Включить ПРМ1'},
    {index: 'I_OFPRM1', id: 112, name: 'Отключить ПРМ1'},
    {index: 'I_ONPRM2', id: 113, name: 'Включить ПРМ2'},
    {index: 'I_OFPRM2', id: 114, name: 'Отключить ПРМ2'},
    {index: 'I_ONPRD1', id: 115, name: 'Включить ПРД1'},
    {index: 'I_OFPRD1', id: 116, name: 'Отключить ПРД1'},
    {index: 'I_ONPRD2', id: 117, name: 'Включить ПРД2'},
    {index: 'I_OFPRD2', id: 118, name: 'Отключить ПРД2'},
    {index: 'I_ANTPRM1', id: 119, name: 'Позиция 1 ПК'},
    {index: 'I_ANTPRM2', id: 120, name: 'Позиция 2 ПК'},
    {index: 'I_ONPF1PRD1', id: 121, name: 'Включить питание ПРД1 от Ф1'},
    {index: 'I_ONPF2PRD1', id: 122, name: 'Включить питание ПРД1 от Ф2'},
    {index: 'I_OFPF1PRD1', id: 123, name: 'Отключить питание ПРД1 от Ф1'},
    {index: 'I_OFPF2PRD1', id: 124, name: 'Отключить питание ПРД1 от Ф2'},
    {index: 'I_ONPF1BK1', id: 125, name: 'Включить питание БК1 от Ф1'},
    {index: 'I_ONPF2BK1', id: 126, name: 'Включить питание БК1 от Ф2'},
    {index: 'I_OFPF1BK1', id: 127, name: 'Отключить питание БК1 от Ф1'},
    {index: 'I_OFPF2BK1', id: 128, name: 'Отключить питание БК1 от Ф2'},
    {index: 'I_ONPF1PRD2', id: 129, name: 'Включить питание ПРД2 от Ф1'},
    {index: 'I_ONPF2PRD2', id: 130, name: 'Включить питание ПРД2 от Ф2'},
    {index: 'I_OFPF1PRD2', id: 131, name: 'Отключить питание ПРД2 от Ф1'},
    {index: 'I_OFPF2PRD2', id: 132, name: 'Отключить питание ПРД2 от Ф2'},
    {index: 'I_ONPF1BK2', id: 133, name: 'Включить питание БК2 от Ф1'},
    {index: 'I_ONPF2BK2', id: 134, name: 'Включить питание БК2 от Ф2'},
    {index: 'I_OFPF1BK2', id: 135, name: 'Отключить питание БК2 от Ф1'},
    {index: 'I_OFPF2BK2', id: 136, name: 'Отключить питание БК2 от Ф2'},
    {index: 'I_OFVIP1UU', id: 137, name: 'Отключить  ВИП1 УУ'},
    {index: 'I_PRDTEST', id: 147, name: 'Включить тестовый режим ПРД'},
    {index: 'I_PRDDATA', id: 163, name: 'Включить режим передачи данных'},
]